# Generated by Django 5.1.4 on 2025-01-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Адрес электронной почты')),
                ('full_name', models.CharField(default=None, null=True, verbose_name='Полное имя сотрудника')),
                ('user_type', models.CharField(choices=[('admin', 'Administrator'), ('worker', 'Worker')], default='worker', max_length=6, verbose_name='Роль сотрудника')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен?')),
                ('is_stuff', models.BooleanField(default=False, verbose_name='Внутренний сотрудник?')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Суперпользователь?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ('full_name',),
            },
        ),
    ]
